var region = ['서울','경기도','충청북도','충청남도','강원도','경상북도','경상남도','전라북도','전라남도'];
var region_array = JSON.stringify(region);

localStorage.setItem('region',region_array);

var ski_resort=['베어스타운리조트','스타힐리조트','곤지암리조트','양지파인리조트','지산리조트','무주덕유산리조트','휘닉스파크','용평리조트','대명비발디파크','웰리힐리파크','한솔오크밸리','하이원리조트','에덴밸리리조트','엘리시안강촌','JY클럽','영헌배리리조트','할리갈리파크','서울중앙리조트','서울스카이스키장','관악리조트','용산스카이밸리스키장','저녁하늘리조트','밤하늘스카이캐슬','인천중앙리조트','인천스카이스키장','인천리조트','인천스카이밸리스키장','충남중앙리조트','충남스카이스키장','충남리조트','충남스카이밸리스키장','충북중앙리조트','충북스카이스키장','충북리조트','충북스카이밸리스키장','대전중앙리조트','대전스카이스키장','대전리조트','대전스카이밸리스키장','경북중앙리조트','경북스카이스키장','경북리조트','경북스카이밸리스키장','경남스카이스키장','경남리조트','경스카이밸리스키장','전북스카이스키장','전북리조트','전북스카이밸리스키장','전남중앙리조트','전남스카이스키장','전남리조트','전남스카이밸리스키장','대구중앙리조트','대구스카이스키장','대구리조트','대구스카이밸리스키장','광주중앙리조트','광주스카이스키장','광주리조트','광주스카이밸리스키장','부산스카이밸리스키장','제주스카이밸리스키장'];
var ski_resort_array= JSON.stringify(ski_resort);
localStorage.setItem('ski_resort',ski_resort_array);

var beartown_price={"대인값":68000,"소인값":52000};
var starhill_price={"대인값":54000,"소인값":38000};
var gonjiam_price={"대인값":64000,"소인값":47000};
var yangji_price={"대인값":39000,"소인값":28000};
var jisan_price={"대인값":66000,"소인값":52000};
var mujuduck_price={"대인값":58000,"소인값":48000};
var phoenix_price={"대인값":62300,"소인값":62300};
var yongpyong_price={"대인값":64000,"소인값":54000};
var deamyong_price={"대인값":72000,"소인값":58000};
var wellihilli_price={"대인값":72000,"소인값":60000};
var hansol_price={"대인값":54000,"소인값":4400};
var high1_price={"대인값":62000,"소인값":49000};
var edenvalley_price={"대인값":46000,"소인값":38000};
var elysian_price={"대인값":65000,"소인값":45000};
var jyclup_price={"대인값":70000,"소인값":50000};
var younghun_price={"대인값":70000,"소인값":50000};
var hallygally_price={"대인값":70000,"소인값":50000};
var seoulmiddle_price={"대인값":70000,"소인값":50000};
var seoulsky_price={"대인값":70000,"소인값":50000};
var gwanak_price={"대인값":70000,"소인값":50000};
var youngsan_price={"대인값":70000,"소인값":50000};
var incheonmiddle_price={"대인값":70000,"소인값":50000};
var incheonsky_price={"대인값":70000,"소인값":50000};
var incheon_price={"대인값":70000,"소인값":50000};
var incheonskyvelly_price={"대인값":70000,"소인값":50000};
var chungnammiddle_price={"대인값":70000,"소인값":50000};
var chungnamsky_price={"대인값":70000,"소인값":50000};
var chungnam_price={"대인값":70000,"소인값":50000};
var chungnamskyvelly_price={"대인값":70000,"소인값":50000};
var chungbukmiddle_price={"대인값":70000,"소인값":50000};
var chungbuksky_price={"대인값":70000,"소인값":50000};
var chungbuk_price={"대인값":70000,"소인값":50000};
var chungbukskyvelly_price={"대인값":70000,"소인값":50000};
var daejeonmiddle_price={"대인값":70000,"소인값":50000};
var daejeonsky_price={"대인값":70000,"소인값":50000};
var daejeon_price={"대인값":70000,"소인값":50000};
var daejeonskyvelly_price={"대인값":70000,"소인값":50000};
var kyongbukmiddle_price={"대인값":70000,"소인값":50000};
var kyongbuksky_price={"대인값":70000,"소인값":50000};
var kyongbuk_price={"대인값":70000,"소인값":50000};
var kyongbuksktvelly_price={"대인값":70000,"소인값":50000};
var kyongnamsky_price={"대인값":70000,"소인값":50000};
var kyongnam_price={"대인값":70000,"소인값":50000};
var kyongnamskyvelly_price={"대인값":70000,"소인값":50000};
var jeonbuksky_price={"대인값":70000,"소인값":50000};
var jeonbuk_price={"대인값":70000,"소인값":50000};
var jeonbukskyvelly_price={"대인값":70000,"소인값":50000};
var jeonnammiddle_price={"대인값":70000,"소인값":50000};
var jeonnamsky_price={"대인값":70000,"소인값":50000};
var jeonnam_price={"대인값":70000,"소인값":50000};
var jeonnamskyvelly_price={"대인값":70000,"소인값":50000};
var gwangjumiddle_price={"대인값":70000,"소인값":50000};
var gwangjusky_price={"대인값":70000,"소인값":50000};
var gwangju_price={"대인값":70000,"소인값":50000};
var gwangjuskyvelly_price={"대인값":70000,"소인값":50000};
var daegumiddle_price={"대인값":70000,"소인값":50000};
var daegusky_price={"대인값":70000,"소인값":50000};
var daegu_price={"대인값":70000,"소인값":50000};
var daeguskyvelly_price={"대인값":70000,"소인값":50000};
var busanskyvelly_price={"대인값":70000,"소인값":50000};
var jejuskyvelly_price={"대인값":70000,"소인값":50000};

var beartwon_price_json=JSON.stringify(beartwon_price);
var starhill_price_json=JSON.stringify(starhill_price);
var gonjiam_price_json=JSON.stringify(gonjiam_price);
var yangji_price_json=JSON.stringify(yangji_price);
var jisan_price_json=JSON.stringify(jisan_price);
var mujuduck_price_json=JSON.stringify(mujuduck_price);
var phoenix_price_json=JSON.stringify(phoenix_price);
var yongpyong_price_json=JSON.stringify(yongpyong_price);
var deamyong_price_json=JSON.stringify(deamyong_price);
var wellihilli_price_json=JSON.stringify(wellihilli_price);
var hansol_price_json=JSON.stringify(hansol_price);
var high1_price_json=JSON.stringify(high1_price);
var edenvalley_price_json=JSON.stringify(edenvalley_price);
var elysian_price_json=JSON.stringify(elysian_price);
var jyclup_price_json=JSON.stringify(jyclup_price);
var younghun_price_json=JSON.stringify(younghun_price);
var hallygally_price_json=JSON.stringify(hallygally_price);
var seoulmiddle_price_json=JSON.stringify(seoulmiddle_price);
var seoulsky_price_json=JSON.stringify(seoulsky_price);
var gwanak_price_json=JSON.stringify(gwanak_price);
var youngsan_price_json=JSON.stringify(younghun_price);
var incheonmiddle_price_json=JSON.stringify(incheonmiddle_price);
var incheonsky_price_json=JSON.stringify(incheonsky_price);
var incheon_price_json=JSON.stringify(incheon_price);
var incheonskyvelly_price_json=JSON.stringify(incheonskyvelly_price);
var chungnammiddle_price_json=JSON.stringify(chungnammiddle_price);
var chungnamsky_price_json=JSON.stringify(chungnamsky_price);
var chungnam_price_json=JSON.stringify(chungnam_price);
var chungnamskyvelly_price_json=JSON.stringify(chungnamskyvelly_price);
var chungbukmiddle_price_json=JSON.stringify(chungbukmiddle_price);
var chungbuksky_price_json=JSON.stringify(chungbuksky_price);
var chungbuk_price_json=JSON.stringify(chungbuk_price);
var chungbukskyvelly_price_json=JSON.stringify(chungbukskyvelly_price);
var daejeonmiddle_price_json=JSON.stringify(daejeonmiddle_price);
var daejeonsky_price_json=JSON.stringify(daejeonsky_price);
var daejeon_price_json=JSON.stringify(daejeon_price);
var daejeonskyvelly_price_json=JSON.stringify(daejeonskyvelly_price);
var kyongbukmiddle_price_json=JSON.stringify(kyongbukmiddle_price);
var kyongbuksky_price_json=JSON.stringify(kyongbuksky_price);
var kyongbuk_price_json=JSON.stringify(kyongbuk_price);
var kyongbuksktvelly_price_json=JSON.stringify(kyongbukskyvelly_price);
var kyongnamsky_price_json=JSON.stringify(kyongnamsky_price);
var kyongnam_price=_json=JSON.stringify(kyongnam_price);
var kyongnamskyvelly_price_json=JSON.stringify(kyongnamskyvelly_price);
var jeonbuksky_price_json=JSON.stringify(jeonbuksky_price);
var jeonbuk_price_json=JSON.stringify(jeonbuk_price);
var jeonbukskyvelly_price_json=JSON.stringify(jeonbukskyvelly_price);
var jeonnammiddle_price_json=JSON.stringify(jeonnammiddle_price);
var jeonnamsky_price_json=JSON.stringify(jeonnamsky_price);
var jeonnam_price_json=JSON.stringify(jeonnam_price);
var jeonnamskyvelly_price_json=JSON.stringify(jeonnamskyvelly_price);
var gwangjumiddle_price_json=JSON.stringify(gwangjumiddle_price);
var gwangjusky_price_json=JSON.stringify(gwangjusky_price);
var gwangju_price_json=JSON.stringify(gwangju_price);
var gwangjuskyvelly_price_json=JSON.stringify(gwangjuskyvelly_price);
var daegumiddle_price_json=JSON.stringify(daegumiddle_price);
var daegusky_price_json=JSON.stringify(daegusky_price);
var daegu_price_json=JSON.stringify(daegu_price);
var daeguskyvelly_price_json=JSON.stringify(daeguskyvelly_price);
var busanskyvelly_price_json=JSON.stringify(busanskyvelly_price);
var jejuskyvelly_price_json=JSON.stringify(jejuskyvelly_price);

window.localStorage.setItem('beartown',beartwon_price_json);
window.localStorage.setItem('starhill',starhill_price_json);
window.localStorage.setItem('gonjiam',gonjiam_price_json);
window.localStorage.setItem('yangji',yangji_price_json);
window.localStorage.setItem('jisan',jisan_price_json);
window.localStorage.setItem('mujuduck',mujuduck_price_json);
window.localStorage.setItem('phoenix',phoenix_price_json);
window.localStorage.setItem('yongpyong',yongpyong_price_json);
window.localStorage.setItem('deamyong',deamyong_price_json);
window.localStorage.setItem('wellihilli',wellihilli_price_json);
window.localStorage.setItem('hansol',hansol_price_json);
window.localStorage.setItem('high1',high1_price_json);
window.localStorage.setItem('edenvalley',edenvalley_price_json);
window.localStorage.setItem('elysian',elysian_price_json);
window.localStorage.setItem('jyclup',jyclup_price_json);
window.localStorage.setItem('younghun',younghun_price_json);
window.localStorage.setItem('hallygally',hallygally_price_json);
window.localStorage.setItem('seoulmiddle',seoulmiddle_price);
window.localStorage.setItem('seoulsky',seoulsky_price);
window.localStorage.setItem('gwanak',gwanak_price);
window.localStorage.setItem('youngsan',youngsan_price);
window.localStorage.setItem('incheonmiddle',incheonmiddle_price);
window.localStorage.setItem('incheonsky',incheonsky_price);
window.localStorage.setItem('incheon',incheon_price);
window.localStorage.setItem('incheonskyvelly',incheonskyvelly_price);
window.localStorage.setItem('chungnammiddle',chungnammiddle_price);
window.localStorage.setItem('chungnamsky',chungnamsky_price);
window.localStorage.setItem('chungnam',chungnam_price);
window.localStorage.setItem('chungnamskyvelly',chungnamskyvelly_price);
window.localStorage.setItem('chungbukmiddle',chungbukmiddle_price);
window.localStorage.setItem('chungbuksky',chungbuksky_price);
window.localStorage.setItem('chungbuk',chungbuk_price);
window.localStorage.setItem('chungbukskyvelly',chungbukskyvelly_price);
window.localStorage.setItem('daejeonmiddle',daejeonmiddle_price);
window.localStorage.setItem('daejeonsky',daejeonsky_price);
window.localStorage.setItem('daejeon',daejeon_price);
window.localStorage.setItem('daejeonskyvelly',daejeonskyvelly_price);
window.localStorage.setItem('kyongbukmiddle',kyongbukmiddle_price);
window.localStorage.setItem('kyongbuksky',kyongbuksky_price);
window.localStorage.setItem('kyongbuk',kyongbuk_price);
window.localStorage.setItem('kyongbuksktvelly',kyongbuksktvelly_price);
window.localStorage.setItem('kyongnamsky',kyongnamsky_price);
window.localStorage.setItem('kyongnam',kyongnam_price);
window.localStorage.setItem('kyongnamskyvelly',kyongnamskyvelly_price);
window.localStorage.setItem('jeonbuksky',jeonbuksky_price);
window.localStorage.setItem('jeonbuk',jeonbuk_price);
window.localStorage.setItem('jeonbukskyvelly',jeonbukskyvelly_price);
window.localStorage.setItem('jeonnammiddle',jeonnammiddle_price);
window.localStorage.setItem('jeonnamsky',jeonnamsky_price);
window.localStorage.setItem('jeonnam',jeonnam_price);
window.localStorage.setItem('jeonnamskyvelly',jeonnamskyvelly_price);
window.localStorage.setItem('gwangjumiddle',gwangjumiddle_price);
window.localStorage.setItem('gwangjusky',gwangjusky_price);
window.localStorage.setItem('gwangju',gwangju_price);
window.localStorage.setItem('gwangjuskyvelly',gwangjuskyvelly_price);
window.localStorage.setItem('daegumiddle',daegumiddle_price);
window.localStorage.setItem('daegusky',daegusky_price);
window.localStorage.setItem('daegu',daegu_price);
window.localStorage.setItem('daeguskyvelly',daeguskyvelly_price);
window.localStorage.setItem('busanskyvelly',busanskyvelly_price);
window.localStorage.setItem('jejuskyvelly',jejuskyvelly_price);
